config/routes.rb
Rails.application.routes.draw do
  get 'ranking', to: 'ranking#index'

  get 'scores/new'

  post 'scores', to: 'scores#create'

  resources :games
  get 'landing/index'

  root to: 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :scores, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :game
  validates :player_email, :score, presence: true
  validates :score, numericality: { greater_than_or_equal_to: 0 }
  validates :player_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  def index
    # Use the service pattern to keep the controller clean of logic, see: app/services/ranking_service.rb
    @ranking = RankingService.new.call
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def new
    @score = Score.new
  end

  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to scores_new_path, notice: 'Score was successfully added.' }
        format.json { render json: @score, status: :created}

      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def score_params
      params.require(:score).permit(:player_email, :game_id, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name, placeholder: :name, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-light" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game, :class => "btn btn-link" %> |
<%= link_to 'Back', games_path, :class => "btn btn-link" %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Set up games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= link_to 'Show', game, :class => "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_game_path(game), :class => "btn btn-link" %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path, :class => "btn btn-light" %>

<br>
<%= link_to 'Back', root_path, :class => "btn btn-link" %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path, :class => "btn btn-link" %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game), :class => "btn btn-link" %> |
<%= link_to 'Back', games_path, :class => "btn btn-link" %>

app/views/landing/index.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= image_tag "game-controller.svg", width: 140, height: 140 %>
    <h2>Set up games</h2>
    <p>List, show, edit or delete games from the high scores service and create new games through an easy web form. The games only need to have a name.</p>
    <p><a class="btn btn-secondary bg-dark" href="<%= games_path %>" role="button">Set up new games</a></p>
  </div>
  <div class="col-lg-4">
    <%= image_tag "score.svg", width: 140, height: 140 %>
    <h2>Add score</h2>
    <p>A form with some fields to manually send the score obtained by a player in one of the games. Remember an API endpoint is also offered for this purpose.</p>
    <p><a class="btn btn-secondary bg-dark" href="<%= scores_new_path %>" role="button">Send a new score</a></p>
  </div>
  <div class="col-lg-4">
    <%= image_tag "ranking.svg", width: 140, height: 140 %>
    <h2>View ranking</h2>
    <p>A screen showing the ranking of the top 10 players. The system uses the position of the max score of each player in each game in order to give them a global ranking.</p>
    <p><a class="btn btn-secondary bg-dark" href="<%= ranking_path %>" role="button">Show top players</a></p>
  </div>
</div>

<hr>
<footer class="footer">
  <div class="container">
    <span class="text-muted">Developed by Manuel Flores Vivas. Credit icons by Flaticon.</span>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>High scores</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <nav class="navbar sticky-top navbar-dark bg-primary">
      <a class="navbar-brand" href="/">High Scores</a>
    </nav>

    <% if params[:controller]=="landing" %>
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-4">High Scores!</h1>
          <p>High score service for a new game console by a well known brand using Ruby on Rails. The games can use a REST API in order to communicate with the service. And to help debugging, the following features are offered.</p>
        </div>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/ranking/index.html.erb
<p></p>

<h1>Ranking</h1>
<p>Global ranking of the top 10 players.</p>

<div>
  <% if @ranking.empty? %>
    <p>No scores yet, please wait until a player finish a game.</p>
  <% else %>
    <table class="table table-striped table-bordered table-responsive-sm">
      <thead>
        <tr>
        <th>Position</th><th>Player email</th><th>Top score</th>
      </tr>
      </thead>
      <tbody>
        <% @ranking.each do |item| %>
          <tr>
            <td>#<%= item.position %></td>
            <td><%= item.player_email %></td>
            <td><%= item.score%> points</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/scores/new.html.erb
<p id="notice">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
</p>

<h1>Add score</h1>
<p>Enter a new score obtained by a player in one of the games.</p>

 <%= form_for @score, url: {action: "create"} do |form| %>

   <% if @score.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

       <ul>
       <% @score.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
   <% end %>

  <div class="field form-group row">
    <div class="col-md-2">
      <%= form.label :player_email, :class => "col-form-label" %>
    </div>
    <div class="col-md-4">
      <%= form.email_field :player_email, id: :player_email, placeholder: :player_email, :class => "form-control" %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-md-2">
      <%= form.label :game, :class => "col-form-label" %>
    </div>
    <div class="col-md-4">
      <%= form.collection_select(:game_id, Game.all, :id, :name, {}, {:class=>"custom-select"}) %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-md-2">
      <%= form.label :score, :class => "col-form-label" %>
    </div>
    <div class="col-md-4">
      <%= form.text_field :score, id: :score, placeholder: :score, :class => "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-light" %>
  </div>
<% end %>

<%= link_to 'Back', root_path, :class => "btn btn-link" %>